import type { Metadata } from "next";
import "./globals.css";
import { LanguageProvider } from "@/features/languages/context/LanguageContext";
import Header from "@/features/navigation/components/Header";
import Footer from "@/components/Blocks/Footer";
import { PlaceRatingProvider } from "@/features/places/usePlaceRating";

export const metadata: Metadata = {
  title: "Golv Mestere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <PlaceRatingProvider>
          <LanguageProvider>
            <Header />
            {children}
            <Footer />
          </LanguageProvider>
        </PlaceRatingProvider>
      </body>
    </html>
  );
}
