import type { Metadata } from "next";
import "./globals.css";
import { LanguageProvider } from "@/features/languages/context/LanguageContext";
import Header from "@/features/navigation/components/Header";

export const metadata: Metadata = {
  title: "Golv Mestere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <LanguageProvider>
          <Header />
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
